api = "0.8"

[buildpack]
  description = "A buildpack that allows an app developer to supply credentials for GIT repositories which require authentication"
  homepage = "https://github.com/anynines/gitcredentials"
  id = "anynines/gitcredentials"
  keywords = ["git", "credentials"]
  name = "GIT credentials"
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "MIT License"
    uri = "https://github.com/anynines/gitcredentials/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build","bin/detect","buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [metadata.configuration]
    default_timeout = "3600"
    default_protocol = "https"
    default_host = "github.com"
    default_path = "/"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "heroku-20"

[[stacks]]
  id = "google"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
