api = "0.2"

[buildpack]
  id = "anynines/gitcredentials"
  name = "GIT credentials"

[metadata]
  include-files = ["bin/build","bin/detect","buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [metadata.configuration]
    default_timeout = "3600"
    default_protocol = "https"
    default_host = "github.com"
    default_path = "/"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "heroku-20"

[[stacks]]
  id = "google"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
