api = "0.2"

[buildpack]
  id = "com.anynines.buildpacks.gitcredentials"
  name = "GIT credentials"
  version = "0.0.7"

[metadata]
  include-files = ["bin/build","bin/detect","buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [metadata.configuration]
    default_timeout = "3600"
    default_protocol = "https"
    default_host = "github.com"
    default_path = "/"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
