[[buildpacks]]
id = "paketo-community/build-plan"
uri = "https://github.com/paketo-community/build-plan/releases/download/v0.0.10/build-plan-0.0.10.tgz"

[[order]]
  [[order.group]]
  id = "paketo-community/build-plan"
  optional = true

[stack]
id = "io.buildpacks.stacks.bionic"

build-image = "anyninesgmbh/build-n-run:base-cnb"
run-image = "anyninesgmbh/build-n-run:base-cnb"
