name: Run tests

on:
  push:
    branches:
    - '*'
    - '!main'

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.18.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Unit Tests
      run: ./scripts/unit.sh

  integration:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2.1.4
      with:
        go-version: 1.18.x
    - name: Checkout
      uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true
    - name: Run Integration Tests
      run: ./scripts/integration.sh --use-token
      env:
        GIT_TOKEN: ${{ github.token }}
